[build]
  command = "npm run build"
  publish = "dist"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle Reddit OAuth callback specifically
[[redirects]]
  from = "/auth/reddit/callback"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "frame-ancestors 'none'; connect-src 'self' https://oauth.reddit.com https://*.supabase.co https://api.perplexity.ai"