export const BRAND = {
  name: 'YFetch',
  colors: {
    primary: {
      DEFAULT: '#3b82f6',
      hover: '#2563eb',
      light: '#60a5fa',
      dark: '#1d4ed8',
    },
    secondary: {
      DEFAULT: '#2563eb',
      hover: '#1d4ed8',
      light: '#3b82f6',
      dark: '#1e40af',
    },
    slate: {
      50: '#f8fafc',
      100: '#f1f5f9',
      200: '#e2e8f0',
      300: '#cbd5e1',
      400: '#94a3b8',
      500: '#64748b',
      600: '#475569',
      700: '#334155',
      800: '#1e293b',
      900: '#0f172a',
    },
    dark: '#f8fafc',
    light: '#1e293b',
    text: {
      primary: 'var(--text-primary)',
      secondary: 'var(--text-secondary)',
      muted: 'var(--text-muted)',
      light: 'var(--text-light)',
    }
  },
  fonts: {
    sans: [
      'ui-sans-serif',
      'system-ui',
      '-apple-system',
      'BlinkMacSystemFont',
      '"Segoe UI"',
      'Roboto',
      '"Helvetica Neue"',
      'Arial',
      '"Noto Sans"',
      'sans-serif',
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
      '"Segoe UI Symbol"',
      '"Noto Color Emoji"',
    ].join(', '),
    mono: [
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      '"Liberation Mono"',
      '"Courier New"',
      'monospace',
    ].join(', '),
  },
  spacing: {
    base: 'var(--spacing-base)',
    xs: 'var(--spacing-xs)',
    sm: 'var(--spacing-sm)',
    lg: 'var(--spacing-lg)',
    xl: 'var(--spacing-xl)',
  },
  logoUrl: '/logo.svg',
  faviconUrl: '/favicon.svg',
} as const;